# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LogSignScreen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LogSignScreen 
   # Pods for maskn
  pod 'TwitterKit'
  pod 'TwitterCore'

  target 'LogSignScreen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LogSignScreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
